//? `luckystack add login` — installs the auth BACKEND (@luckystack/login, which
//? self-wires session + OAuth-by-env via its `./register` subpath on restart) AND
//? reproduces what an auth-mode scaffold ships, so the result actually WORKS:
//?   - copies the editable consumer-owned auth surface into the project (skip-if-
//?     exists): the /login,/register,/reset-password,/settings pages + their _api
//?     handlers + LoginForm + the `functions/session.ts` shim (exposes
//?     `functions.session.*` in every handler — the _api handlers need it) +
//?     `server/hooks/notifications.ts` (sign-in / password-change emails).
//?   - restores config.ts auth flags an `auth: 'none'` scaffold disabled
//?     (credentials:false → true, forgotPassword:'disabled' → 'framework').
//?   - registers the notification hooks in luckystack/server/index.ts.
//? The config + server edits are BEST-EFFORT: a project already in the auth shape
//? (or one the user customized) simply skips them rather than failing the add.

import fs from 'node:fs';
import path from 'node:path';
import {
  addDependency,
  assetPath,
  copyDirIfAbsent,
  editFile,
  err,
  hasDependency,
  ok,
  resolveLuckyStackRange,
  runNpmInstall,
  toError,
  type ConsumerProject,
  type Result,
} from '../lib/project';
import type { AddOptions } from './addPresence';
import { deriveOrm, readScaffoldOrm } from '../lib/state';

//? The auth-hooks block a credentials scaffold ships in luckystack/server/index.ts.
//? Mirror of the scaffolder's pre-prune content (so add+prune are inverse).
export const AUTH_SERVER_HOOKS = `import { registerHook, resolveEnvKey } from '@luckystack/core';
import { registerNotificationHooks } from '../../server/hooks/notifications';

//? Wires the transactional notification hooks (new sign-in email,
//? password-change email). Reads \`user.preferences\` to respect opt-in. Safe
//? to leave on even if @luckystack/email isn't installed — the email
//? sender no-ops with \`{ ok: false, reason: 'no-sender' }\`.
registerNotificationHooks();

//? Example dev-only logger — delete or replace with your own audit hook.
registerHook('postLogin', ({ userId, provider, isNewUser }) => {
  if (resolveEnvKey() !== 'production') {
    console.log(\`[hooks] login: user=\${userId}, provider=\${provider}, new=\${String(isNewUser)}\`);
  }
  return undefined;
});`;

export const AUTH_NONE_SERVER_PLACEHOLDER = `//? authMode 'none': no auth hooks to register. Add your own framework-hook
//? registrations here (this overlay is auto-imported at boot, after every
//? other overlay file).
export {};`;

//? Best-effort file edit: returns whether it applied. A token-miss means the file
//? is already in the target shape (or the user customized it) — skip, don't fail.
const tryEdit = (filePath: string, find: string, replace: string): boolean => {
  if (!fs.existsSync(filePath)) return false;
  try {
    editFile(filePath, [{ find, replace }]);
    return true;
  } catch {
    return false;
  }
};

//? ORM-aware auth wiring (ADR 0020). The default UserAdapter is Prisma-backed;
//? on a non-Prisma data layer `add login` ADAPTS instead of assuming Prisma:
//? it writes a per-ORM starter `luckystack/login/userAdapter.ts` (commented,
//? complete against the real UserAdapter interface — the consumer uncomments
//? + creates the users table) and names exactly which copied settings routes
//? still call `functions.db.prisma` and need porting.

//? Settings `_api` routes in the copied asset bundle that reach the database
//? DIRECTLY via `functions.db.prisma` (not through the UserAdapter). Keep in
//? step with `assets/login/src/settings/_api/`.
const PRISMA_BOUND_SETTINGS_ROUTES = [
  'src/settings/_api/changePassword_v1.ts',
  'src/settings/_api/updateUser_v1.ts',
  'src/settings/_api/updatePreferences_v1.ts',
  'src/settings/_api/deleteAccount_v1.ts',
  'src/settings/_api/requestEmailChange_v1.ts',
  'src/settings/_api/confirmEmailChange_v1.ts',
];

const DRIZZLE_USER_ADAPTER_STARTER = `//? Custom UserAdapter starter — data layer: DRIZZLE (generated by \`luckystack add login\`).
//? The built-in login UserAdapter is Prisma-backed; this file wires auth to
//? your drizzle client instead. Two steps to activate:
//?
//? 1. Add a users table to server/db/schema.ts (pg-core flavor shown — adjust
//?    the imports/columns to your dialect, then \`npm run db:push\`):
//?
//?      export const users = pgTable('users', {
//?        id: serial('id').primaryKey(),
//?        createdAt: timestamp('created_at').defaultNow().notNull(),
//?        email: text('email').notNull(),
//?        password: text('password'),
//?        provider: text('provider').notNull().default('credentials'),
//?        name: text('name'),
//?        avatar: text('avatar').notNull().default(''),
//?        avatarFallback: text('avatar_fallback').notNull().default(''),
//?        language: text('language').notNull().default('en'),
//?        theme: text('theme').notNull().default('light'),
//?      });
//?
//? 2. Uncomment everything below. (mysql2 note: \`.returning()\` is Postgres/
//?    SQLite — on mysql re-select the row after insert/update instead.)

// import { registerUserAdapter, type UserAdapter, type UserRecord } from '@luckystack/login';
// import { and, asc, eq } from 'drizzle-orm';
// import { db } from '../../functions/db';
// import { users } from '../../server/db/schema';
//
// const toRecord = (row: typeof users.$inferSelect): UserRecord =>
//   ({ ...row, id: String(row.id) }) as UserRecord;
//
// const adapter: UserAdapter = {
//   findByEmail: async ({ email, provider }) => {
//     const [row] = await db.select().from(users)
//       .where(and(eq(users.email, email), eq(users.provider, provider))).limit(1);
//     return row ? toRecord(row) : null;
//   },
//   findByEmailAnyProvider: async ({ email }) => {
//     const [row] = await db.select().from(users)
//       .where(eq(users.email, email)).orderBy(asc(users.createdAt)).limit(1);
//     return row ? toRecord(row) : null;
//   },
//   findById: async (id) => {
//     const [row] = await db.select().from(users).where(eq(users.id, Number(id))).limit(1);
//     return row ? toRecord(row) : null;
//   },
//   create: async (input) => {
//     const [row] = await db.insert(users).values({
//       email: input.email,
//       provider: input.provider,
//       name: input.name ?? null,
//       password: input.password ?? null,
//       avatar: input.avatar ?? '',
//       avatarFallback: input.avatarFallback ?? '',
//       language: input.language ?? 'en',
//     }).returning();
//     return toRecord(row);
//   },
//   update: async (id, patch) => {
//     const { id: _id, ...data } = patch;
//     const [row] = await db.update(users).set(data).where(eq(users.id, Number(id))).returning();
//     return toRecord(row);
//   },
//   delete: async (id) => {
//     await db.delete(users).where(eq(users.id, Number(id)));
//   },
// };
//
// registerUserAdapter(adapter);

export {};
`;

const MIKRO_USER_ADAPTER_STARTER = `//? Custom UserAdapter starter — data layer: MIKRO-ORM (generated by \`luckystack add login\`).
//? The built-in login UserAdapter is Prisma-backed; this file wires auth to
//? your MikroORM EntityManager instead. Two steps to activate:
//?
//? 1. Define the User entity (EntitySchema, no decorators) in
//?    server/db/entities.ts and add it to \`entities\` in
//?    server/db/mikro-orm.config.ts, then \`npm run db:schema:update\`:
//?
//?      export interface User {
//?        id: number; createdAt: Date; email: string; password: string | null;
//?        provider: string; name: string | null; avatar: string;
//?        avatarFallback: string; language: string; theme: string;
//?      }
//?      export const UserSchema = new EntitySchema<User>({
//?        name: 'User',
//?        properties: {
//?          id: { type: 'number', primary: true, autoincrement: true },
//?          createdAt: { type: 'Date', onCreate: () => new Date() },
//?          email: { type: 'string' },
//?          password: { type: 'string', nullable: true },
//?          provider: { type: 'string', default: 'credentials' },
//?          name: { type: 'string', nullable: true },
//?          avatar: { type: 'string', default: '' },
//?          avatarFallback: { type: 'string', default: '' },
//?          language: { type: 'string', default: 'en' },
//?          theme: { type: 'string', default: 'light' },
//?        },
//?      });
//?      (MongoDB: use \`_id: { type: 'ObjectId', primary: true }\` +
//?       \`id: { type: 'string', serializedPrimaryKey: true }\` instead.)
//?
//? 2. Uncomment everything below.

// import { registerUserAdapter, type UserAdapter, type UserRecord } from '@luckystack/login';
// import { getEm } from '../../functions/db';
// import type { User } from '../../server/db/entities';
//
// const toRecord = (user: User | null): UserRecord | null =>
//   user ? ({ ...user, id: String(user.id) }) as UserRecord : null;
//
// const adapter: UserAdapter = {
//   findByEmail: async ({ email, provider }) =>
//     toRecord(await (await getEm()).findOne<User>('User', { email, provider })),
//   findByEmailAnyProvider: async ({ email }) =>
//     toRecord(await (await getEm()).findOne<User>('User', { email }, { orderBy: { createdAt: 'asc' } })),
//   findById: async (id) =>
//     toRecord(await (await getEm()).findOne<User>('User', { id: Number(id) })),
//   create: async (input) => {
//     const em = await getEm();
//     const user = em.create<User>('User', {
//       email: input.email,
//       provider: input.provider,
//       name: input.name ?? null,
//       password: input.password ?? null,
//       avatar: input.avatar ?? '',
//       avatarFallback: input.avatarFallback ?? '',
//       language: input.language ?? 'en',
//     });
//     await em.persistAndFlush(user);
//     return toRecord(user) as UserRecord;
//   },
//   update: async (id, patch) => {
//     const em = await getEm();
//     const user = await em.findOneOrFail<User>('User', { id: Number(id) });
//     const { id: _id, ...data } = patch;
//     em.assign(user, data);
//     await em.flush();
//     return toRecord(user) as UserRecord;
//   },
//   delete: async (id) => {
//     const em = await getEm();
//     await em.nativeDelete('User', { id: Number(id) });
//   },
// };
//
// registerUserAdapter(adapter);

export {};
`;

const NONE_USER_ADAPTER_STARTER = `//? Custom UserAdapter starter — data layer: NONE (generated by \`luckystack add login\`).
//? The built-in login UserAdapter is Prisma-backed; implement this interface
//? against YOUR data layer (whatever functions/db.ts exports) and uncomment
//? the registration. Full contract + a drizzle example:
//? node_modules/@luckystack/login/docs/user-adapter.md

// import { registerUserAdapter, type UserAdapter } from '@luckystack/login';
//
// const adapter: UserAdapter = {
//   findByEmail: async ({ email, provider }) => { /* TODO */ return null; },
//   findByEmailAnyProvider: async ({ email }) => { /* TODO */ return null; },
//   findById: async (id) => { /* TODO */ return null; },
//   create: async (input) => { /* TODO */ throw new Error('UserAdapter.create not implemented'); },
//   update: async (id, patch) => { /* TODO */ throw new Error('UserAdapter.update not implemented'); },
//   delete: async (id) => { /* TODO */ },
// };
//
// registerUserAdapter(adapter);

export {};
`;

const USER_ADAPTER_STARTERS: Record<string, string> = {
  drizzle: DRIZZLE_USER_ADAPTER_STARTER,
  'mikro-orm': MIKRO_USER_ADAPTER_STARTER,
  none: NONE_USER_ADAPTER_STARTER,
};

//? Write the per-ORM starter adapter (skip-if-exists — the consumer owns the
//? file). Exported for reuse by the ORM switcher: switching a login-enabled
//? project to another data layer needs the same starter (cross-dimension
//? interplay — the steps react to each other).
export const writeUserAdapterStarterFor = (project: ConsumerProject, orm: string): void => {
  const adapterPath = path.join(project.root, 'luckystack', 'login', 'userAdapter.ts');
  const starter = USER_ADAPTER_STARTERS[orm];
  if (starter && !fs.existsSync(adapterPath)) {
    fs.mkdirSync(path.dirname(adapterPath), { recursive: true });
    fs.writeFileSync(adapterPath, starter);
    console.log(`• wrote a ${orm} UserAdapter starter to luckystack/login/userAdapter.ts (finish its two steps to activate auth)`);
  }
};

//? Detect the data layer and, when it is not Prisma, write the matching
//? starter adapter + spell out what still needs porting. Non-blocking: a
//? finished custom adapter is a fully supported setup.
const adaptAuthToDataLayer = (project: ConsumerProject): void => {
  const orm = deriveOrm({
    hasPackage: (pkg) => hasDependency(project.pkg, pkg),
    scaffoldOrm: readScaffoldOrm(project.root),
  });
  if (orm === 'prisma') return;

  writeUserAdapterStarterFor(project, orm);

  console.warn(
    `\n⚠ Data layer is '${orm}' — the built-in login UserAdapter is Prisma-backed.\n` +
      '  To make auth work here:\n' +
      '  1. Finish luckystack/login/userAdapter.ts (starter written above; create the users table + uncomment).\n' +
      '  2. Port (or remove) the copied settings routes that still call functions.db.prisma directly:\n' +
      PRISMA_BOUND_SETTINGS_ROUTES.map((route) => `       - ${route}`).join('\n') +
      '\n  Full contract + examples: node_modules/@luckystack/login/docs/user-adapter.md\n',
  );
};

export const addLogin = (project: ConsumerProject, options: AddOptions): Result<void> => {
  adaptAuthToDataLayer(project);
  //? Copy the WHOLE auth bundle (src/ UI + functions/session.ts + server/hooks)
  //? into the project (idempotent, skip-if-exists so consumer edits are kept).
  //? IMPORTANT: the list of files/dirs this copies is the authoritative surface that
  //? `remove login` (LOGIN_COPIED_PATHS in remove.ts) must delete to stay symmetric.
  //? If you add a file to assets/login/, also add it to LOGIN_COPIED_PATHS in remove.ts.
  let written: string[];
  try {
    written = copyDirIfAbsent(assetPath('login'), project.root);
  } catch (error) {
    return err(toError(error));
  }
  if (written.length > 0) {
    console.log(`• copied ${String(written.length)} auth file(s) into the project (pages + _api + LoginForm + functions/session.ts + server/hooks/notifications.ts)`);
  } else {
    console.log('• auth files already present — skipped copy (kept your edits).');
  }

  const range = resolveLuckyStackRange(project.pkg, options.cliVersion);
  try {
    if (addDependency(project, '@luckystack/login', range)) {
      console.log(`• added @luckystack/login@${range} to package.json`);
    }
  } catch (error) {
    return err(toError(error));
  }

  //? Re-enable auth in config.ts if an `auth: 'none'` scaffold had disabled it.
  const configRestored = tryEdit(
    path.join(project.root, 'config.ts'),
    `  auth: {
    //? authMode 'none': no built-in auth UI/flows are scaffolded.
    forgotPassword: 'disabled',
    credentials: false,
  },`,
    `  auth: {
    forgotPassword: 'framework',
    credentials: true,
  },`,
  );
  if (configRestored) console.log("• re-enabled auth in config.ts (credentials: true, forgotPassword: 'framework')");

  //? Register the notification hooks in the server overlay (reverse of the prune).
  const hooksWired = tryEdit(
    path.join(project.root, 'luckystack', 'server', 'index.ts'),
    AUTH_NONE_SERVER_PLACEHOLDER,
    AUTH_SERVER_HOOKS,
  );
  if (hooksWired) console.log('• registered notification hooks in luckystack/server/index.ts');

  if (options.install) {
    console.log('• running npm install …');
    if (!runNpmInstall(project.root, project.pkg)) {
      console.warn('  npm install failed — run it manually to finish.');
    }
  } else {
    console.log('• skipped npm install (--no-install) — run `npm install` to finish.');
  }

  console.log('\n✓ login added. Restart the server + run `npm run generateArtifacts`. The auth backend self-wires');
  console.log('  from env (set DEV_<PROVIDER>_CLIENT_ID/SECRET to enable an OAuth provider; add the');
  console.log('  provider origin to EXTERNAL_ORIGINS in .env, or use `npx luckystack manage` → Auth).');
  console.log('  For framework-mode forgot-password / email-change, also: npx luckystack add email');
  //? Page-load ROUTE GUARDS are consumer-owned and NOT auto-edited (a scaffold with
  //? auth:none routes '/' → /dashboard and leaves the dashboard ungated). Surfacing
  //? this so a developer doesn't ship an unauthenticated dashboard unknowingly.
  console.log('\n⚠ Route guards are not auto-wired. If you want auth-gated routing, add a page guard:');
  console.log('    • src/dashboard/page.tsx: export const middleware = ({ session }) => session');
  console.log('        ? { success: true } : { success: false, redirect: \'/login\' };');
  console.log('    • src/page.tsx: redirect \'/\' to /login (or your entry) when there\'s no session.');
  console.log('  See docs/luckystack/LUCKYSTACK_ADD_GUIDE.md (add login → route guards).');
  return ok();
};
