//? `luckystack upgrade` — READ-ONLY. Gathers everything an AI (or developer) needs
//? to upgrade LuckyStack and writes it to `dump/UPGRADE_PLAN.md` (a fixed, findable
//? path), then prints a summary. It mutates nothing: it detects the installed
//? version, lists the CHANGELOGs to read (in node_modules), and lays out the exact
//? step sequence + gotchas so the plan is deterministic instead of prose an AI has
//? to reconstruct. Full narrative runbook: docs/luckystack/UPGRADING.md.

import fs from 'node:fs';
import path from 'node:path';
import { type ConsumerProject } from '../lib/project';

interface InstalledPackage {
  name: string;
  version: string;
  changelog: string | null;
}

//? Read every installed `@luckystack/*` package from node_modules with its version
//? and CHANGELOG path (relative to the project root, so the plan links are copy-pasteable).
const readInstalledPackages = (root: string): InstalledPackage[] => {
  const scopeDir = path.join(root, 'node_modules', '@luckystack');
  if (!fs.existsSync(scopeDir)) return [];
  const packages: InstalledPackage[] = [];
  for (const entry of fs.readdirSync(scopeDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const pkgPath = path.join(scopeDir, entry.name, 'package.json');
    if (!fs.existsSync(pkgPath)) continue;
    let version = '?';
    try {
      const parsed = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { version?: string };
      if (typeof parsed.version === 'string') version = parsed.version;
    } catch {
      //? A malformed package.json shouldn't crash the read-only plan.
    }
    const changelogAbs = path.join(scopeDir, entry.name, 'CHANGELOG.md');
    packages.push({
      name: `@luckystack/${entry.name}`,
      version,
      changelog: fs.existsSync(changelogAbs) ? path.relative(root, changelogAbs).split(path.sep).join('/') : null,
    });
  }
  return packages.toSorted((a, b) => a.name.localeCompare(b.name));
};

//? Build the AI-readable plan markdown. `today` is injected so the caller controls
//? the date (and tests stay deterministic).
export const buildUpgradePlan = (
  installed: InstalledPackage[],
  today: string,
  hasManifest: boolean,
  target: string | null,
): string => {
  const core = installed.find((p) => p.name === '@luckystack/core');
  const installedVersion = core?.version ?? '(unknown — @luckystack/core not in node_modules; run `npm install` first)';
  const changelogs = installed.filter((p) => p.changelog !== null);
  const priority = ['@luckystack/core', '@luckystack/server', '@luckystack/cli', 'create-luckystack-app', '@luckystack/login'];
  const orderedChangelogs = [
    ...priority.map((n) => changelogs.find((p) => p.name === n)).filter((p): p is InstalledPackage => p !== undefined),
    ...changelogs.filter((p) => !priority.includes(p.name)),
  ];

  return `# LuckyStack upgrade plan

> Generated by \`luckystack upgrade\` on ${today}. READ-ONLY — nothing was changed.
> Narrative runbook: docs/luckystack/UPGRADING.md.

- **Installed version:** ${installedVersion}
- **Target version:** ${target ?? 'latest — run `npm view @luckystack/core version` to get the number'}
- **Scaffold manifest:** ${hasManifest ? 'present → `luckystack update --app` can overwrite-if-pristine' : 'MISSING (pre-0.4.1 project) → `update` runs SIDECAR-ONLY (every differing file gets a `.new` twin; nothing overwritten)'}
- **Installed @luckystack/* packages:** ${installed.length}

## 1. Read the gap (don't bump silently)
Read these CHANGELOGs for entries BETWEEN the installed and target version, then
tell the user what's new — ESPECIALLY security (2FA / email-code login) and any
\`### Changed\` behaviour flip (e.g. logger timestamps default-on since 0.6.3):

${orderedChangelogs.length > 0 ? orderedChangelogs.map((p) => `- ${p.name} (installed ${p.version}) → \`${p.changelog}\``).join('\n') : '- (no CHANGELOGs found — run `npm install` first, then re-run `luckystack upgrade`)'}

If a CHANGELOG has no entry for the installed version (historical 0.2–0.4 gaps),
also read that package's \`node_modules/@luckystack/<pkg>/CLAUDE.md\` "Config keys"
section + \`docs/luckystack/decisions/*.md\`.

## 2. Surface + OFFER
Ask the user whether to adopt any new feature. Never enable one they didn't ask for.

## 3. Bump + install (developer action)
Set every \`@luckystack/*\` (incl. the \`@luckystack/cli\` devDep) to the same target
version in package.json, then \`npm install\`.

## 4. Refresh in-tree files
\`npx luckystack update\` then \`npx luckystack update --app\` — new framework files
delivered; files you edited get a \`<file>.new\` sidecar + a merge note in
\`dump/UPDATE_*.log\`.${hasManifest ? '' : ' (Sidecar-only mode — see above.)'}

## 5. Merge sidecars + adopt features
Merge each \`.new\`. A NEW optional package → \`npx luckystack add <feature>\`
(\`luckystack list\` shows options). A feature TOGGLE on an installed package (2FA) →
config flag + schema columns (manual, fails loudly) + prerequisites, per its runbook
(\`docs/luckystack/ARCHITECTURE_AUTH.md\` for 2FA).

## 6. Verify
\`npm run generateArtifacts\` → \`npm run typecheck\` → smoke-test → commit.
`;
};

export const runUpgrade = (project: ConsumerProject, target: string | null, now: Date): void => {
  const installed = readInstalledPackages(project.root);
  const today = now.toISOString().slice(0, 10);
  const hasManifest = fs.existsSync(path.join(project.root, '.luckystack', 'scaffold.json'));
  const plan = buildUpgradePlan(installed, today, hasManifest, target);

  const dumpDir = path.join(project.root, 'dump');
  fs.mkdirSync(dumpDir, { recursive: true });
  const outPath = path.join(dumpDir, 'UPGRADE_PLAN.md');
  fs.writeFileSync(outPath, plan, 'utf8');

  const core = installed.find((p) => p.name === '@luckystack/core');
  console.log(`luckystack upgrade — ${project.root}`);
  console.log(`  installed @luckystack/core: ${core?.version ?? '(not installed — run npm install first)'}`);
  console.log(`  target: ${target ?? 'latest (run `npm view @luckystack/core version`)'}`);
  console.log(`  ${installed.length} @luckystack/* packages, ${installed.filter((p) => p.changelog).length} CHANGELOGs to read`);
  console.log(`\n→ Wrote the AI-readable upgrade plan to dump/UPGRADE_PLAN.md`);
  console.log(`  Full runbook: docs/luckystack/UPGRADING.md`);
};
