//? Foundational session-shape types. These live in @luckystack/core (not
//? @luckystack/login) because core's `validateRequest` consumes them, and
//? a login → core dep already exists for prisma/redis. Putting these in
//? login would create a circular type dep that breaks per-package dts builds.
//?
//? @luckystack/login re-exports these from its barrel, so existing project
//? code (`import type { BaseSessionLayout } from '@luckystack/login'`)
//? keeps working.

export interface SessionLocation {
  pathName: string;
  searchParams?: Record<string, string>;
}

export interface BaseSessionLayout {
  id: string;
  //? @adr 0018 — OPTIONAL on the base so a CLIENT-facing session type
  //? (`ClientSessionLayout` = the project session minus the server-only
  //? credential fields) still satisfies the `T extends BaseSessionLayout` bound
  //? used by the client session context / hooks / `useSocket`. Server-side session
  //? types (the project's own `SessionLayout`) redeclare `token: string` as
  //? REQUIRED, so server handlers keep their strict typing — the base is relaxed,
  //? not the server contract. Core never reads `token` off a base-typed value.
  token?: string;
  email?: string | null;
  name?: string | null;
  avatar?: string | null;
  avatarFallback?: string | null;
  admin?: boolean | null;
  language?: string | null;
  location?: SessionLocation;
  roomCodes?: string[];
  /**
   * CSRF token bound to this session. Generated by `saveSession` on first
   * write. Validated by the HTTP handler on state-changing requests when
   * the session is in cookie mode. Token-mode sessions don't need this
   * (cross-origin requests don't auto-attach a sessionStorage value).
   */
  csrfToken?: string;
  /**
   * Most recent successful login time (set to "now" on each login). Optional
   * — populated only when the User schema has a `lastLogin` column.
   */
  lastLogin?: Date | string | null;
  /**
   * The previous successful login time, captured at this login's moment.
   * Useful for "Last sign-in: X ago" UI on the post-login dashboard.
   * Null on first-ever login. Runtime-only — not persisted to the DB.
   */
  previousLogin?: Date | string | null;
}

export interface AuthProps {
  /** If true, user must have a valid session with an ID */
  login: boolean;

  /** Additional validation rules for session properties */
  additional?: {
    /** The session property to check (e.g., 'admin', 'email') */
    key: keyof BaseSessionLayout;

    /** Exact value the property must equal (strict comparison) */
    value?: unknown;

    /** Type the property must be */
    type?: 'string' | 'number' | 'boolean';

    /** If true, property must be null/undefined. If false, must NOT be null/undefined */
    nullish?: boolean;

    /** If true, property must be falsy. If false, must be truthy */
    mustBeFalsy?: boolean;
  }[];
}
