/* eslint-disable */
//? Server entry. Parses positional argv first (so `config.ts` sees the
//? port), loads env, runs side-effect imports for the major config
//? registries, then hands off to `bootstrapLuckyStack` which auto-imports
//? the `luckystack/<package>/` overlay folder and calls
//? `createLuckyStackServer`.
//?
//? Argv shape:  npm run server -- <bundle[,bundle...]> [port]
//? Examples:
//?   npm run server                              (default preset, port 80)
//?   npm run server -- billing                   (one bundle, port 80)
//?   npm run server -- billing,vehicles 4001     (two bundles merged, port 4001)

import '@luckystack/server/parseArgv';

import { config as loadEnv } from 'dotenv';
loadEnv({ path: '.env' });
loadEnv({ path: '.env.local', override: true });

//? Side-effect imports — these populate registries that everything below
//? reads from. Order matters: project config first, then deploy/services.
import '../config';
import '../deploy.config';
import '../services.config';

import type { IncomingMessage, ServerResponse } from 'node:http';
import { bootstrapLuckyStack } from '@luckystack/server';

(async () => {
  //? Minimal static-file fallbacks. Most apps will swap these out for
  //? Vite-built static handlers in production; the server just needs SOME
  //? handler if you serve any static asset alongside `/api` and `/sync`.
  const noopServeFile = (_req: IncomingMessage, res: ServerResponse) => {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Not Found');
  };
  const noopServeFavicon = (res: ServerResponse) => {
    res.writeHead(204);
    res.end();
  };

  //? `loadGeneratedMaps` lets the framework wire production runtime maps
  //? without you having to maintain `server/prod/runtimeMaps.ts`. The first
  //? positional argv arg selects the preset(s) (comma-separated for multi-
  //? preset boots; defaults to `default`). Generated by
  //? `scripts/generateServerRequests.ts` at build time.
  const server = await bootstrapLuckyStack({
    serveFile: noopServeFile,
    serveFavicon: noopServeFavicon,
    loadGeneratedMaps: (preset: string) => import(`./prod/generatedApis.${preset}`),
  });

  await server.listen();
})().catch((err) => {
  console.error('[server] failed to start:', err);
  process.exit(1);
});
